version: '3.8'

networks:
  fast-foodie-network:
    driver: bridge

services:
  fast-foodie-api:
    image: ${GHCR_REGISTRY}/${OWNER_LC}/fast-foodie-api:${SHA}
    container_name: fast-foodie-api
    restart: always
    env_file: .env
    volumes:
      - upload:/app/public/files
    ports:
      - '8000:8000'
    depends_on:
      - fast-foodie-db
    networks:
      - fast-foodie-network

  fast-foodie-db:
    image: 'postgres:14.5-alpine'
    command: postgres -c 'max_connections=1000'
    restart: always
    container_name: fast-foodie-db
    environment:
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - fast-foodie-network

volumes:
  upload:
  db:
