export const foodIcons = {
  pomme: '🍎',
  banane: '🍌',
  raisin: '🍇',
  orange: '🍊',
  fraise: '🍓',
  pastèque: '🍉',
  ananas: '🍍',
  cerise: '🍒',
  citron: '🍋',
  poire: '🍐',
  pêche: '🍑',
  kiwi: '🥝',
  tomate: '🍅',
  avocat: '🥑',
  carotte: '🥕',
  maïs: '🌽',
  brocoli: '🥦',
  'pomme de terre': '🥔',
  aubergine: '🍆',
  concombre: '🥒',
  'hot-dog': '🌭',
  hamburger: '🍔',
  frites: '🍟',
  pizza: '🍕',
  sushi: '🍣',
  taco: '🌮',
  burrito: '🌯',
  glace: '🍦',
  gâteau: '🍰',
  cookie: '🍪',
  donut: '🍩',
  café: '☕',
  bière: '🍺',
  vin: '🍷',
  cocktail: '🍸',
  flour: '🌾',
  farine: '🌾',
  oeufs: '🥚',
  poulet: '🍗',
  fromage: '🧀',
  lait: '🥛',
  pain: '🍞',
  beurre: '🧈',
  oignon: '🧅',
  ail: '🧄',
  laitue: '🥬',
  épinard: '🥬',
  poivron: '🌶️',
  champignon: '🍄‍🟫',
  sel: '🧂',
  sucre: '🍚',
  chocolat: '🍫',
  thé: '🍵',
  miel: '🍯',
  caramel: '🍯',
  'pain de mie': '🍞',
  riz: '🍚',
  soupe: '🍲',
  salade: '🥗',
  pâtes: '🍝',
  nouilles: '🍜',
  'gâteau au chocolat': '🍫🍰',
  crêpes: '🥞',
  'pain au chocolat': '🥐🍫',
  quiche: '🥧',
  muffin: '🧁',
  biscuit: '🍪',
  'barre granola': '🍫',
  yaourt: '🍦',
  'fromage blanc': '🧀',
  saucisse: '🌭',
  escalope: '🍗',
  steak: '🥩',
  saucisson: '🌭',
  dinde: '🍗',
  poisson: '🐟',
  crevettes: '🦐',
  homard: '🦞',
  huître: '🦪',
  moules: '🦑',
  lamproie: '🐟',
  scampi: '🦐',
  calmar: '🦑',
  langouste: '🦞',
  écrevisse: '🦞',
  sardines: '🐟',
  thon: '🐟',
  truite: '🐟',
  bar: '🐟',
  hareng: '🐟',
  carpe: '🐟',
  perche: '🐟',
  anguille: '🐍',
  crabe: '🦀',
  tartare: '🍣',
  sashimi: '🍣',
  tiramisu: '🍮',
  fondue: '🍲',
  churros: '🍩',
  croissant: '🥐',
  baguette: '🥖',
  pâtisserie: '🍰',
  pâté: '🍖',
  cassoulet: '🍲',
  ratatouille: '🍲',
  'pot-au-feu': '🍲',
  'salade niçoise': '🥗',
  'boeuf bourguignon': '🥩🍷',
  'coq au vin': '🍗🍷',
  'blanquette de veau': '🍖🍲',
  'rôti de porc': '🍖',
  'osso buco': '🍖🍲',
  'salade composée': '🥗',
  'moules frites': '🦪🍟',
  'gratin dauphinois': '🥔🧀',
  quenelles: '🍲',
  clafoutis: '🍒🍰',
  'crème brûlée': '🍮',
  'soufflé au fromage': '🍲🧀',
  'gratin de courgettes': '🥒🧀',
  'gratin de pommes de terre': '🥔🧀',
  'salade de fruits': '🍓🍇🍊',
  compote: '🍏🍎',
  "soupe à l'oignon": '🍲🧅',
  'moules marinières': '🦪🍷',
  'grilled cheese': '🍞🧀',
  'poisson grillé': '🐟🔥',
  'steak haché': '🥩🍔',
  'poulet rôti': '🍗🔥',
  'salade de riz': '🍚🥗',
  'salade de pâtes': '🍝🥗',
  'salade de tomates': '🍅🥗',
  'salade verte': '🥬🥗',
  'tomates farcies': '🍅🍽️',
  'chou farci': '🥬🍽️',
  'soupe de poisson': '🍲🐟',
  hummus: '🍲',
  falafel: '🍲',
  shakshuka: '🍳🍅',
  'poulet au curry': '🍗🌶️',
  'curry de légumes': '🍛🥕',
  'curry de poisson': '🍛🐟',
  'pizza margarita': '🍕🍅🍧',
  'pizza 4 fromages': '🍕🧀🧀🧀🧀',
  'pizza au saumon': '🍕🐟',
  'pizza au jambon': '🍕🥩',
  'pizza au chorizo': '🍕🌶️',
  'saucisson sec': '🌭🧀',
  'fromage râpé': '🧀🧀',
  'grilled chicken': '🍗🔥',
  'cheese burger': '🍔🧀',
};
